huggingface:
  repo_name: "brightertiger/garbled-text-detector"
  organization: null
  private: false
  commit_message: "Upload garbled text detection model"
  
deployment:
  output_dir: "hf_model"
  save_only: false
  
model:
  description: "Binary text classifier for detecting garbled/corrupted text"
  task: "binary-classification"
  tags:
    - "text-classification"
    - "binary-classification"
    - "garbled-text-detection"
    - "bert"
    - "pytorch"
  
license:
  type: "apache-2.0"