model:
  name: "huawei-noah/TinyBERT_General_4L_312D"
  max_length: 512
  dropout: 0.1
  quantization: false
  quantized_inference: false
  use_onnx: false
  onnx_optimization: false

data:
  data_dir: "data"
  train_file: "train.csv"
  val_file: "validation.csv"
  test_file: "test.csv"
  text_column: "text"
  label_column: "label"
  val_split: 0.2

training:
  num_epochs: 3
  batch_size: 16
  learning_rate: 2e-5
  weight_decay: 0.01
  warmup_steps: 100
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1

hardware:
  devices: "auto"
  precision: "16-mixed"
  num_workers: 4
  auto_detect_gpu: true

logging:
  use_wandb: false
  project_name: "pygarble-classification"
  log_every_n_steps: 50

callbacks:
  early_stopping:
    patience: 3
    monitor: "val_loss"
    mode: "min"
  model_checkpoint:
    dirpath: "data/model"
    filename: "garbled-text-detector-best"
    monitor: "val_loss"
    mode: "min"
    save_top_k: 1
    save_last: false
